[tool.poetry]
authors = []
description = ""
name = "yanic"
version = "1.0.0"

[tool.poetry.dependencies]
blacksheep = "^1.2.17"
python = "^3.10.0"
uvicorn = "^0.22.0"
yt-dlp = "~2023.3.4"

[tool.poetry.group.dev.dependencies]
aiohttp = "^3.8.1"
pytest = "~7.2.2"
pytest-asyncio-cooperative = "^0.30.0"
schemathesis = "^3.19.5"
shiv = "^1.0.3"
validators = "^0.20.0"

[tool.poetry.scripts]
server = "yanic.server:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
