[tool.poetry]
authors = ["Listenbox <hello@listenbox.app>"]
description = "async yt-dlp server"
name = "yanic"
version = "1.0.0"

[tool.poetry.dependencies]
python = "^3.8"

blacksheep = "^1.2.17"
uvicorn = "^0.24.0.post1"
yt-dlp = "^2023.06.22"
# because uvicorn:    https://github.com/encode/uvicorn/blob/master/uvicorn/_types.py
# because blacksheep: https://github.com/Neoteroi/BlackSheep/blob/main/blacksheep/asgi.pyi
typing-extensions = "^4.7.1"

[tool.poetry.group.dev.dependencies]
aiohttp = "^3.8.1"
pytest = "^7.4.0"
pytest-asyncio-cooperative = "^0.31.0"
# schemathesis = "^3.19.5"
shiv = "^1.0.3"
validators = "^0.22.0"

[tool.poetry.scripts]
server = "yanic.server:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
